# ################################
# Model: CTC ASR on TIMIT with CRDNN (with LiGRU)
# Additions: SpecAugment - LibriSpeech Basic Policy
# Authors: Gianfranco Dumoulin Bertucci 2025
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/augment_noise_CRDNN/<seed>
test_wer_file: !ref <output_folder>/wer_test.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: !PLACEHOLDER  # e.g. /path/to/TIMIT
train_annotation: !ref <save_folder>/train.json
valid_annotation: !ref <save_folder>/dev.json
test_annotation: !ref <save_folder>/test.json
skip_prep: False # Skip data preparation
uppercase: False # Must be True when the TIMIT dataset is in the upper-case version

####################### Training Parameters ####################################
number_of_epochs: 50
batch_size: 16
lr: 0.0011
sorting: ascending # choose between ascending, descending and random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

####################### Model Parameters #######################################
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
cnn_kernelsize: (3, 3)
rnn_layers: 4
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512

# Outputs
output_neurons: 40
blank_index: 0

# Dataloader options
num_workers: 4
train_dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

valid_dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

test_dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

############################## Augmentations ###################################

# Time drop (T = 100 frames)
time_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
    drop_length_low: 100
    drop_length_high: 101
    drop_count_low: 1
    drop_count_high: 1

# Frequency drop (F = 13~14 on 40 mel bands), scaled from 27 on 80 mel bands
freq_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
    drop_length_low: 13
    drop_length_high: 14
    drop_count_low: 1
    drop_count_high: 1
    dim: 2

# Time warp
time_warp: !new:speechbrain.augment.freq_domain.Warping
    warp_window: 80
    warp_mode: bicubic
    dim: 1

min_num_aug: 1
num_aug: 1
batch_multiplier: 0 # 0/1 -> no batch multiplication
concat_original: False
aug_strategy: 'all'

toggle_time_drop: True
toggle_freq_drop: True
toggle_time_warp: True

fea_augment: !new:speechbrain.augment.new_augmenter.NewAugmenter
    augmentations: [
        !ref <time_drop>,
        !ref <freq_drop>,
        !ref <time_warp>
    ]
    min_num_aug: !ref <min_num_aug>
    num_aug: !ref <num_aug>
    batch_multiplier: !ref <batch_multiplier>
    concat_original: !ref <concat_original>
    aug_strategy: !ref <aug_strategy>
    aug_toggles: [
        !ref <toggle_time_drop>,
        !ref <toggle_freq_drop>,
        !ref <toggle_time_warp>
    ]


############################## Models ##########################################

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

model: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_size: !ref <n_mels>
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

weight_decay: 0.04
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9,0.95)
    weight_decay: !ref <weight_decay>

n_warmup_steps: 1800
lr_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr>
    n_warmup_steps: !ref <n_warmup_steps>

modules:
    model: !ref <model>
    output: !ref <output>
    normalize: !ref <normalize>

jit_module_keys: [model]

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        output: !ref <output>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
